### ISSUE TITLE
Rocket fires when git pull fails

### ISSUE THREAD

**Issue by williamfiset** [bomanimc/gitrocket#4]
Sometimes the git rocket fires even when the "git push" command fails. Are you checking the return status the git push command and making sure it's zero before firing the rocket?

![screen shot 2017-10-14 at 9 41 22 pm](https://user-images.githubusercontent.com/5898848/31581834-9839c8d4-b128-11e7-8861-847abe4946a0.png)

**Comment by bomanimc** [comment]
Thanks for leaving this issue! PR #5 should fix this issue once it's released. I'll leave this open until I merge it and release a new version.

**Comment by bomanimc** [comment]
This should be fixed in version 1.0.5 of gitrocket. Please reopen if you're still having the issue!
