### ISSUE TITLE
[Future Request] Landing rocket when pulling

### ISSUE THREAD

**Issue by favna** [bomanimc/gitrocket#7]
If the rocket is launched when pushing it only makes sense to have it land when pulling and hey thanks to pappa Elon Musk we sure are no strangers anymore to the concept of landing rockets ;)

**Comment by bomanimc** [comment]
Good idea! That seems like it wouldn't be too hard to add. Feel free to submit a PR if you're interested! Otherwise, I might have some time to check this out in the future.

**Comment by favna** [comment]
At best I could look into it when I'm back from vacation so depending on your own time you may have time before I do.

**Comment by Ickerday** [comment]
https://www.npmjs.com/package/space-pull
There's a plugin for that now. :)
